// GENERATED FILE — DO NOT EDIT.

export const CIRCUIT_OPEN_MS = 30000 as const;
export const DEFAULT_FALLBACK_TIMEOUT_MS = 30000 as const;
export const DIRECT_PATH_SUFFIX = "chat/completions" as const;
export const DIRECT_HEADER_NAMES: ReadonlySet<string> = new Set(['accept', 'content-type', 'idempotency-key', 'user-agent']);
export const DIRECT_HEADER_PREFIXES = ['openai-', 'x-stainless-'] as const;
export const SAFE_GATEWAY_STATUSES: ReadonlySet<number> = new Set([502, 503, 504]);
export const PROVIDER_IDS = ['openai', 'anthropic', 'gemini'] as const;
export type ProviderKeyName = (typeof PROVIDER_IDS)[number];
export const HEADER_DEVICE_ID = "x-abto-device-id" as const;
export const HEADER_FEATURE_ID = "x-abto-feature-id" as const;
export const HEADER_PROVIDER_KEY_PREFIX = "x-abto-key-" as const;
export const HEADER_REQUEST_ID = "x-abto-request-id" as const;
export const HEADER_ATTEMPT = "x-abto-attempt" as const;
export const HEADER_PROVIDER = "x-abto-provider" as const;
export const HEADER_ERROR_SOURCE = "x-abto-error-source" as const;
export const SERVER_CONFORMANCE_SCENARIOS = ['config.api_key_required', 'config.gateway_base_url_required', 'config.gateway_base_url_from_env', 'fallback.destination_required', 'fallback.destination_alone_enables', 'fallback.rejected_without_openai_key', 'fallback.off_when_unconfigured', 'fallback.timeout_validated', 'fallback.switches_on_connect_failure', 'fallback.switches_on_admission_503', 'fallback.no_switch_on_ambiguous_timeout', 'fallback.no_switch_on_ambiguous_disconnect', 'fallback.replays_timeout_when_opted_in', 'fallback.sends_to_configured_destination', 'fallback.direct_error_returned_as_is', 'security.rejects_cross_origin_request', 'security.replaces_spoofed_context_headers', 'security.rejects_provider_key_injection', 'context.propagates_and_isolates', 'context.emits_only_configured_identifiers', 'retry.official_default_preserved', 'retry.caller_setting_preserved', 'circuit.shared_across_clients', 'circuit.closes_on_gateway_recovery', 'provider_key.resolved_per_request'] as const;
export const ERR_FALLBACK_BASE_URL_REQUIRED = "[abto] fallback.baseURL is required to enable OpenAI direct fallback. Set it to the OpenAI-compatible endpoint this application used before ABTO." as const;
export const ERR_FALLBACK_BASE_URL_INVALID = "[abto] fallback.baseURL must be a valid http(s) URL." as const;
export const ERR_FALLBACK_OPENAI_KEY_REQUIRED = "[abto] fallback.baseURL is set but no OpenAI provider key is available. Direct fallback sends the request with that key, so configure it or remove the fallback setting." as const;
export const ERR_FALLBACK_TIMEOUT_POSITIVE = "[abto] fallback.timeoutMs must be greater than 0." as const;
export const ERR_GATEWAY_BASE_URL_INVALID = "[abto] gatewayBaseURL must be a valid http(s) URL." as const;
export const ERR_GATEWAY_BASE_URL_REQUIRED = "[abto] gatewayBaseURL is required. Pass it explicitly or set ABTO_GATEWAY_BASE_URL." as const;
export const ERR_API_KEY_REQUIRED = "[abto] abtoApiKey is required. Pass it explicitly or set ABTO_API_KEY." as const;
export const ERR_GATEWAY_REQUEST_URL_INVALID = "[abto] Gateway request URL is invalid." as const;
export const ERR_GATEWAY_ORIGIN_REFUSED = "[abto] Refusing to send credentials outside the configured Gateway origin." as const;
export const ERR_API_KEY_INVALID_CHARACTERS = "[abto] abtoApiKey contains invalid characters." as const;
export const ERR_PROVIDER_KEY_INVALID_CHARACTERS = "[abto] Provider key for {provider} contains invalid characters." as const;
